import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain.agents import create_agent

from tools import search, get_weather, get_flights

# Load environment variables
load_dotenv()

# LLM
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

# Tools list
tools = [
    search,
    get_weather,
    get_flights
]

# System prompt exactly preserved from existing agent
system_prompt = """
    You are an AI Travel Assistant.

    Your job is to help users plan their travel.

    Follow this process:

    STEP 1:
    Identify the state or country mentioned by the user.

    STEP 2:
    Use the search tool to find the capital city.

    STEP 3:
    If the user asks for weather, use the weather tool
    with the capital city.

    STEP 4:
    If the user asks for flights, a travel date is required.

    If the user wants flights but has not provided a travel date,
    ask the user to provide the travel date.

    STEP 5:
    When flights are requested, use the search tool to find
    the IATA airport code of the capital city.

    For example, if the capital is Chennai, search for:
    "Chennai airport IATA code"

    Do NOT use hardcoded city-to-IATA mappings.

    STEP 6:
    Use the flight tool with the IATA code and travel date.

    STEP 7:
    Give the user a clear final response.

    Never invent weather or flight information.
    Use the tools whenever external/current information is required.
    """

# Agent creation
agent = create_agent(
    model=llm,
    tools=tools,
    system_prompt=system_prompt
)


def ask_travel_agent(user_query: str) -> str:
    """
    Invokes the LangChain travel agent with the user's query
    and returns the final text response.
    """
    response = agent.invoke({
        "messages": [
            {
                "role": "user",
                "content": user_query
            }
        ]
    })

    messages = response.get("messages", [])
    if messages:
        last_msg = messages[-1]
        if hasattr(last_msg, "content"):
            content = last_msg.content
        elif isinstance(last_msg, dict):
            content = last_msg.get("content", "")
        else:
            content = str(last_msg)

        if isinstance(content, list):
            text_parts = []
            for part in content:
                if isinstance(part, str):
                    text_parts.append(part)
                elif isinstance(part, dict) and "text" in part:
                    text_parts.append(part.get("text", ""))
            return "\n".join(text_parts)

        return str(content)

    return "No response generated by agent."
